theme: jekyll-theme-minimal
title: CMSC320 Final Project - The Effects of Screen Time on Mental Health
description: As a group we have chosen to analysis the effects of Screen Time on Mental Health for the CMSC320 Final Project
